# Day 7 — Ring evaluation

**This is the first notebook that uses `isFraud` for anything graph-related** — and it's used only to *evaluate* the clusters built blind on Days 5-6, never to build them. See the discussion in [docs/identity-graph.md](../docs/identity-graph.md) for why that separation is what makes this evaluation genuine rather than circular.

In [1]:
import sys, json
sys.path.append('..')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from src.data import load_merged_train
from src.graph import load_graph
from src.ring_eval import cluster_stats, evaluate_flagged_clusters, classify_cluster_edge_types

train = load_merged_train()

identity_graph = load_graph('../data/processed/identity_graph.pkl')
behavioral_graph = load_graph('../data/processed/behavioral_graph.pkl')

with open('../data/processed/cluster_partition.json') as f:
    partition_raw = json.load(f)
partition = {int(k): v for k, v in partition_raw.items()}

print('Loaded', len(partition), 'transactions across', len(set(partition.values())), 'clusters')

Loaded 590540 transactions across 265011 clusters

In [2]:
train['cluster_id'] = train['TransactionID'].map(partition)

population_fraud_rate = train['isFraud'].mean()
total_fraud = int(train['isFraud'].sum())
print(f'Population fraud rate: {population_fraud_rate:.4f} ({total_fraud:,} fraud transactions total)')

stats = cluster_stats(train['TransactionID'], train['cluster_id'], train['isFraud'])
non_trivial_stats = stats[stats['size'] > 1]
print(f'Non-trivial clusters: {len(non_trivial_stats):,}')

Population fraud rate: 0.0350 (20,663 fraud transactions total)

Non-trivial clusters: 40,451

## 1. Did blind clustering actually find fraud?

"Flagged" = every transaction inside a non-trivial cluster is treated as a positive prediction. This is the headline check: does grouping by shared card/address/email/behavior — done with zero knowledge of which transactions are fraud — actually concentrate real fraud?

In [3]:
result_min2 = evaluate_flagged_clusters(stats, min_size=2, total_fraud=total_fraud, population_fraud_rate=population_fraud_rate)

print(f"Clusters flagged (size >= 2): {result_min2['n_clusters_flagged']:,}")
print(f"Transactions flagged: {result_min2['n_transactions_flagged']:,}")
print(f"Fraud captured: {result_min2['n_fraud_captured']:,}")
print(f"Precision (fraud % within flagged clusters): {result_min2['precision']:.4f}")
print(f"Fraud lift vs. population baseline ({population_fraud_rate:.4f}): {result_min2['lift']:.2f}x")
print(f"Capture rate (% of ALL fraud found inside flagged clusters): {result_min2['capture_rate']:.4f}")

Clusters flagged (size >= 2): 40,451
Transactions flagged: 365,980
Fraud captured: 15,151
Precision (fraud % within flagged clusters): 0.0414
Fraud lift vs. population baseline (0.0350): 1.18x
Capture rate (% of ALL fraud found inside flagged clusters): 0.7332

## 2. Sensitivity check: does this hold at different ring-size thresholds?

A finding that only shows up at exactly one arbitrary cutoff isn't trustworthy. Cluster size is known before any label is looked at, so it's used here as the ring-definition threshold — checking min sizes 2, 3, and 5.

In [4]:
sensitivity = pd.DataFrame([
    evaluate_flagged_clusters(stats, min_size=m, total_fraud=total_fraud, population_fraud_rate=population_fraud_rate)
    for m in [2, 3, 5]
]).set_index('min_size')

sensitivity

,n_clusters_flagged,n_transactions_flagged,n_fraud_captured,precision,lift,capture_rate
min_size,,,,,,
2,40451,365980,15151,0.041398,1.183150,0.733243
3,17499,320076,13374,0.041784,1.194164,0.647244
5,6629,284079,11960,0.042101,1.203228,0.578812

## 3. Does the behavioral layer earn its place?

Day 6 showed 94.2% of behavioral edges connect transactions with no shared identity attribute — a structural finding. Now check the part that actually matters: do clusters found **only** through behavioral similarity (no identity edge inside them at all) still concentrate real fraud, or is that similarity coincidental?

In [5]:
edge_types = classify_cluster_edge_types(partition, identity_graph, behavioral_graph)

non_trivial_stats = non_trivial_stats.copy()
non_trivial_stats['has_identity'] = non_trivial_stats.index.map(lambda c: edge_types['has_identity'].get(c, False))
non_trivial_stats['has_behavioral'] = non_trivial_stats.index.map(lambda c: edge_types['has_behavioral'].get(c, False))

def category(row):
    if row['has_identity'] and row['has_behavioral']:
        return 'both'
    if row['has_identity']:
        return 'identity_only'
    if row['has_behavioral']:
        return 'behavioral_only'
    return 'neither'

non_trivial_stats['category'] = non_trivial_stats.apply(category, axis=1)

summary = non_trivial_stats.groupby('category').apply(
    lambda g: pd.Series({
        'n_clusters': len(g),
        'n_transactions': g['size'].sum(),
        'n_fraud': g['fraud_count'].sum(),
        'fraud_rate': g['fraud_count'].sum() / g['size'].sum(),
    }),
    include_groups=False,
)
summary['lift_vs_population'] = summary['fraud_rate'] / population_fraud_rate
summary

,n_clusters,n_transactions,n_fraud,fraud_rate,lift_vs_population
category,,,,,
behavioral_only,18485.0,45662.0,2402.0,0.052604,1.503398
both,8854.0,285483.0,12053.0,0.042220,1.206621
identity_only,13112.0,34835.0,696.0,0.019980,0.571017

In [6]:
behavioral_only_count = (non_trivial_stats['category'] == 'behavioral_only').sum()
print(f"Clusters found ONLY via behavioral similarity (no shared identifier at all): {behavioral_only_count:,}")
print(f"Their combined fraud rate: {summary.loc['behavioral_only', 'fraud_rate']:.4f} "
      f"({summary.loc['behavioral_only', 'lift_vs_population']:.2f}x population baseline)" 
      if 'behavioral_only' in summary.index else 'No behavioral-only clusters found.')

Clusters found ONLY via behavioral similarity (no shared identifier at all): 18,485
Their combined fraud rate: 0.0526 (1.50x population baseline)

## 4. Manual false-positive audit

A handful of larger flagged clusters with **zero** fraud, inspected by hand for a plausible innocent explanation rather than assumed to be a system failure.

In [7]:
false_positive_clusters = non_trivial_stats[non_trivial_stats['fraud_rate'] == 0].sort_values('size', ascending=False)
print(f'Non-trivial clusters with zero fraud: {len(false_positive_clusters):,} of {len(non_trivial_stats):,}')

audit_cols = ['TransactionID', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'addr1', 'P_emaildomain', 'TransactionDT']

for cluster_id in false_positive_clusters.head(5).index:
    members = train[train['cluster_id'] == cluster_id][audit_cols].sort_values('TransactionDT')
    print(f'\n--- Cluster {cluster_id} (size {len(members)}, fraud_rate 0) ---')
    print(members.to_string(index=False))

Non-trivial clusters with zero fraud: 36,866 of 40,451

--- Cluster 13673 (size 411, fraud_rate 0) ---
 TransactionID  TransactionAmt ProductCD  card1  card2  addr1 P_emaildomain  TransactionDT
       2994974          26.000         W   7638  174.0  330.0     gmail.com         246348
       2995575          93.950         W   7638  174.0  330.0     yahoo.com         254998
       2996933         300.000         W   7638  174.0  123.0   hotmail.com         310969
       2997188          78.500         W  10112  360.0  299.0     gmail.com         316827
       2997206          87.000         W   2455  321.0  441.0     gmail.com         317154
       2997208         100.000         H  13844  583.0  315.0    icloud.com         317195
       2997210         120.000         H  16659  170.0  325.0       aol.com         317231
       2997225          66.950         W   4806  490.0  315.0       aol.com         317466
       2997461          50.000         S   6741  583.0  330.0           NaN         321946
       2998600         171.000         W   7638  174.0  272.0     gmail.com         339252
       2999225          44.500         W  11204  298.0  272.0   hotmail.com         347594
       2999596          40.000         W  11204  298.0  272.0     gmail.com         353799
       3000557         221.990         W  13844  583.0  204.0     yahoo.com         398715
       3000725          25.000         W   7638  174.0  494.0           NaN         401634
       3000762         300.000         R   6741  583.0  184.0 anonymous.com         402096
       3000810          50.000         H  13844  583.0  299.0       aol.com         402792
       3000830          15.000         H   8719  555.0  220.0   hotmail.com         403029
       3001080         117.000         W  15651  417.0  330.0     yahoo.com         406169
       3001091          92.000         W   2803  100.0  264.0     gmail.com         406343
       3001103         250.000         R   6741  583.0  226.0 anonymous.com         406567
       3001110          82.990         W   7638  174.0  126.0     gmail.com         406634
       3001112         108.000         W   7815  161.0  181.0     yahoo.com         406670
       3001723         150.000         R  13844  583.0  272.0     gmail.com         414330
       3002220          25.000         H  13844  583.0  226.0 sbcglobal.net         420546
       3002285          48.950         W  11204  298.0  272.0           NaN         421332
       3002505         107.000         W   7638  174.0  181.0     gmail.com         423881
       3002550          25.950         W   6741  583.0  264.0           NaN         424428
       3002804          60.000         W   7638  174.0  330.0     yahoo.com         427877
       3003176          36.950         W   7638  174.0  433.0     yahoo.com         432580
       3003288          20.000         H  16326  321.0  226.0     gmail.com         433887
       3003289          30.000         H  12260  236.0  204.0     gmail.com         433913
       3003299          21.950         W   8528  215.0  272.0           NaN         434034
       3003332          25.000         H  13844  583.0  204.0   hotmail.com         434464
       3003333          34.500         W   7638  174.0  204.0     gmail.com         434479
       3003618         100.000         H   6741  583.0  299.0     gmail.com         438547
       3004225         159.950         W  11204  298.0  272.0           NaN         451866
       3004340          32.970         W   7638  174.0  269.0     gmail.com         468591
       3004392          75.000         H  13844  583.0  330.0     gmail.com         476008
       3004652         100.000         H  13844  583.0  204.0     gmail.com         484259
       3004655          25.000         H  15747  555.0  472.0     yahoo.com         484291
       3004661          25.000         H  16435  298.0  337.0   hotmail.com         484425
       3004698         100.000         H   6019  583.0  264.0     gmail.com         485073
       3004911         311.950         W  13844  583.0  330.0   comcast.net         488299
       3004922         209.950         W  13844  583.0  330.0   comcast.net         488452
       3005211         100.000         H   6741  583.0  264.0     yahoo.com         493009
       3005719         300.000         R   6019  583.0  310.0     gmail.com         499867
       3005730          87.950         W  11204  298.0  272.0     yahoo.com         499994
       3005741         209.950         W  16435  298.0  337.0     yahoo.com         500077
       3005850         209.950         W  16435  298.0  337.0     yahoo.com         501619
       3005859         270.000         W  18268  583.0  184.0   comcast.net         501693
       3005880         374.950         W   3532  555.0  420.0     gmail.com         502114
       3006206          25.000         W   7638  174.0  330.0     gmail.com         506430
       3006379         200.000         R   6741  583.0  184.0 anonymous.com         508951
       3006381          40.000         W   7638  174.0  494.0     gmail.com         509007
       3006408         250.000         R   6741  583.0  472.0 anonymous.com         509335
       3006820          50.000         H   1333  170.0  299.0       cox.net         514970
       3007176          50.000         S   6741  583.0  330.0           NaN         519424
       3007188          15.000         S  16435  298.0  337.0           NaN         519596
       3007191          15.000         S  16435  298.0  337.0           NaN         519612
       3007193          15.000         S  16435  298.0  337.0           NaN         519649
       3007198          15.000         S  16435  298.0  337.0           NaN         519701
       3007202          15.000         S  16435  298.0  337.0           NaN         519753
       3007207          20.000         S  13844  583.0  126.0           NaN         519809
       3007222         100.000         S   6741  583.0  330.0           NaN         519955
       3007227          10.000         S  16435  298.0  337.0           NaN         520018
       3007351        1000.000         R   1333  170.0  264.0 anonymous.com         521711
       3007432          67.950         W  11280  481.0  272.0     gmail.com         522911
       3007713          50.000         H  13281  396.0  226.0     gmail.com         528085
       3007718          20.000         S   1724  583.0  184.0           NaN         528135
       3008259          35.000         H  13844  583.0  472.0     yahoo.com         561746
       3008289          25.000         S  13844  583.0  203.0           NaN         563587
       3008410         100.000         W   7182  396.0  315.0     yahoo.com         567757
       3008535          30.950         W  13844  583.0  110.0           NaN         571019
       3008649          55.950         W  16435  298.0  184.0       aol.com         573601
       3008724         100.000         W   7638  174.0  494.0     yahoo.com         574680
       3008773          25.000         S   6741  583.0  330.0           NaN         575688
       3008897        2014.970         W   6741  583.0  330.0           NaN         577447
       3008898         699.950         W   7676  512.0  299.0     yahoo.com         577449
       3008899         450.000         R   7487  399.0  469.0     yahoo.com         577522
       3008919         527.000         W   8431  269.0  325.0     yahoo.com         577734
       3008921         611.940         W  11280  481.0  126.0           NaN         577765
       3009107          20.000         S  16435  298.0  337.0           NaN         580306
       3009134         400.000         R  10203  396.0  299.0 anonymous.com         580628
       3009198         275.990         W   1333  170.0  205.0       aol.com         581876
       3009202         250.000         R   6741  583.0  469.0   hotmail.com         581960
       3009281         100.000         R  10476  404.0  299.0 anonymous.com         583218
       3009300          50.000         W   1974  111.0  184.0     gmail.com         583472
       3009306          57.950         W   2114  396.0  315.0           NaN         583529
       3009434         150.000         W  11204  298.0  272.0   hotmail.com         585389
       3009462         100.000         R   6741  583.0  264.0 anonymous.com         585809
       3009475          50.000         H  13844  583.0  204.0       cox.net         586027
       3009488          40.000         H  10476  404.0  177.0     gmail.com         586150
       3009632         100.000         H   4067  445.0  325.0       aol.com         588311
       3009846          29.500         W   7638  174.0  433.0     gmail.com         591363
       3009985         234.970         W  15066  170.0  299.0     gmail.com         593217
       3009989          25.000         H  10023  111.0  325.0     gmail.com         593262
       3009991          30.000         H  13844  583.0  433.0     gmail.com         593279
       3010019         200.000         H  18132  567.0  299.0     gmail.com         593642
       3010033          30.000         H  11204  298.0  272.0     gmail.com         593814
       3010040         213.000         W   2114  396.0  315.0     gmail.com         593886
       3010042         200.000         R   1333  170.0  184.0 anonymous.com         593899
       3010168          31.950         W   1333  170.0  126.0     gmail.com         595729
       3010431          75.000         W  12570  462.0  191.0     yahoo.com         599025
       3010493         209.950         W   4067  199.0  123.0     yahoo.com         599947
       3010644          75.000         H  13844  583.0  325.0 anonymous.com         602359
       3010648          75.000         W  12544  321.0  441.0     yahoo.com         602428
       3010665          75.000         W   7182  396.0  327.0     yahoo.com         602771
       3010683           5.000         W  16435  298.0  337.0           NaN         602974
       3010695         150.000         W   4067  199.0  123.0       att.net         603123
       3010804         150.000         W   4067  199.0  512.0   hotmail.com         604705
       3010813          18.950         W  10854  593.0  264.0     gmail.com         604852
       3010874          25.000         H   3682  264.0  264.0     yahoo.com         605821
       3010881          50.000         H  13844  583.0  315.0 anonymous.com         605864
       3010904          50.000         H  18268  583.0  325.0     gmail.com         606140
       3011053          50.000         R   4067  445.0  325.0 anonymous.com         608505
       3011079          50.000         H   6019  583.0  191.0     ymail.com         608938
       3011088         400.000         W   4067  199.0  512.0       aol.com         609054
       3011305        1000.000         R   6741  583.0  299.0     yahoo.com         612527
       3011321         250.000         R   6741  583.0  299.0     yahoo.com         612806
       3011432        1000.000         R   6741  583.0  387.0     yahoo.com         615159
       3011440        1000.000         R   6741  583.0  387.0     yahoo.com         615401
       3011444        1000.000         R   6741  583.0  387.0     yahoo.com         615489
       3011518          78.500         W  14092  111.0  308.0   hotmail.com         617256
       3011764          59.000         W   6741  583.0  299.0     yahoo.com         626917
       3011863         405.970         W   4067  199.0  123.0     gmail.com         647085
       3011893          50.000         H  16435  298.0  204.0   comcast.net         649685
       3011896        1878.870         W  16435  298.0  337.0       aol.com         649899
       3011923         200.000         R   6741  583.0  204.0     yahoo.com         651174
       3011940          25.000         H  16435  298.0  337.0       aol.com         652137
       3011941          30.000         H  13844  583.0  476.0     gmail.com         652165
       3011964          75.000         W  12570  462.0  191.0     yahoo.com         652648
       3011977          83.500         W  12570  462.0  191.0     yahoo.com         653057
       3011998          50.000         W  12570  462.0  191.0     yahoo.com         653699
       3012140          50.000         W  12570  462.0  191.0     yahoo.com         657101
       3012180         100.000         R   6741  583.0  272.0 anonymous.com         657900
       3012182          75.000         H  13844  583.0  143.0     yahoo.com         657948
       3012190         100.000         R  16075  514.0  327.0     gmail.com         658088
       3012210          80.000         H   1724  583.0  420.0     yahoo.com         658434
       3012269          70.000         H  10476  404.0  126.0 optonline.net         659574
       3012447          90.000         W   4067  199.0  181.0   hotmail.com         662651
       3012460         200.000         R  12213  371.0  330.0   comcast.net         662803
       3012472         200.000         H   6741  583.0  325.0 anonymous.com         662978
       3012495         300.000         S  16435  298.0  337.0           NaN         663325
       3012551          75.000         H  13844  583.0  177.0   hotmail.com         664163
       3012580          50.000         S   6741  583.0  330.0           NaN         664516
       3012734         150.000         R   6741  583.0  184.0 anonymous.com         666606
       3012770          50.000         H   6741  583.0  184.0       aol.com         666990
       3012772          50.000         H   9263  399.0  251.0   hotmail.com         666998
       3012791          50.000         R  16075  514.0  204.0     yahoo.com         667205
       3012912          54.500         W  10476  298.0  184.0     yahoo.com         668657
       3013053         100.000         H   6741  583.0  264.0 anonymous.com         670276
       3013127         250.000         R   6741  583.0  310.0 anonymous.com         671088
       3013165         150.000         R   6741  583.0  184.0 anonymous.com         671540
       3013400          82.950         W  10854  593.0  485.0   hotmail.com         674639
       3013417         214.000         W   4067  199.0  123.0           NaN         674788
       3013930         118.020         W  10854  593.0  158.0     gmail.com         681674
       3013957         422.500         W  13844  583.0  325.0           NaN         681969
       3013968          50.000         W   4067  199.0  512.0   comcast.net         682136
       3013982         513.950         W  10616  583.0  315.0           NaN         682278
       3013999         300.000         R  15528  111.0  384.0   comcast.net         682509
       3014010         422.500         W  13844  583.0  325.0           NaN         682652
       3014024         239.950         W   5901  583.0  181.0           NaN         682788
       3014025         652.370         W  13844  583.0  126.0   outlook.com         682792
       3014026         559.950         W  15066  170.0  441.0 optonline.net         682805
       3014298          25.000         H  12213  371.0  512.0 anonymous.com         686458
       3014326         554.000         W   8394  490.0  204.0     gmail.com         686873
       3014431         312.000         W   4067  199.0  194.0           NaN         688662
       3014718         218.000         W  16435  298.0  337.0           NaN         693345
       3014753          87.990         W   4214  462.0  272.0 anonymous.com         693842
       3014890          50.000         H   5901  583.0  126.0       aol.com         696046
       3015196          30.000         W  10854  593.0  485.0           NaN         702253
       3015204          50.000         W  14092  111.0  308.0     yahoo.com         702535
       3015600          43.970         W   4067  199.0  325.0           NaN         732353
       3015790          20.000         S  13844  583.0  330.0           NaN         740268
       3015861          99.000         W  12570  462.0  191.0     yahoo.com         742040
       3015897          80.000         W   4067  199.0  325.0           NaN         743056
       3015909          83.950         W   4067  199.0  325.0     gmail.com         743271
       3015947         394.950         W  15066  170.0  204.0       aol.com         743993
       3015965         438.140         W   6741  583.0  299.0     gmail.com         744209
       3016005          59.000         W  16435  298.0  337.0     gmail.com         744888
       3016042         200.000         W  10854  593.0  444.0           NaN         745360
       3016051         100.000         H  15528  111.0  384.0   comcast.net         745533
       3016055         226.000         W  10854  593.0  444.0           NaN         745582
       3016058          50.000         W   4067  199.0  123.0     yahoo.com         745636
       3016075          57.950         W   4067  199.0  123.0     yahoo.com         745851
       3016239         150.000         R  13844  583.0  325.0 anonymous.com         748381
       3016243          50.000         H   5901  583.0  143.0   comcast.net         748440
       3016266          50.000         H   6019  583.0  472.0     gmail.com         748681
       3016278          68.950         W  16435  298.0  337.0     yahoo.com         748922
       3016310          53.970         W   8394  490.0  325.0     yahoo.com         749362
       3016364          59.000         W  17055  393.0  264.0     gmail.com         749991
       3016375         250.000         R   6019  583.0  330.0   comcast.net         750164
       3016392          50.000         W  10854  593.0  485.0     yahoo.com         750390
       3016405         250.000         R   6741  583.0  325.0 anonymous.com         750589
       3016416          59.000         W  10854  593.0  485.0           NaN         750672
       3016476          50.000         W  12570  462.0  191.0     yahoo.com         751446
       3016485         100.000         H  10616  583.0  337.0 anonymous.com         751501
       3016494         100.000         R  15682  399.0  325.0   verizon.net         751586
       3016505         100.000         H   7664  490.0  264.0     yahoo.com         751742
       3016506         100.000         R   7585  553.0  184.0 anonymous.com         751755
       3016510         125.000         R   6741  583.0  330.0   comcast.net         751787
       3016527          55.000         W   8394  490.0  325.0     gmail.com         751947
       3016532         100.000         H  10023  111.0  325.0     yahoo.com         752025
       3016537          40.000         S  13844  583.0  330.0           NaN         752079
       3016549          25.000         S  10616  583.0  325.0           NaN         752269
       3016552         100.000         R   8394  490.0  126.0 anonymous.com         752311
       3016555         100.000         H   7585  553.0  337.0   verizon.net         752329
       3016646          59.000         W  10854  593.0  485.0     yahoo.com         753574
       3016650          30.000         W   8394  490.0  325.0       aol.com         753589
       3016692          49.000         W  12570  462.0  191.0     yahoo.com         754123
       3016698          54.500         W   4067  199.0  325.0     gmail.com         754213
       3016708          50.000         W  10854  593.0  485.0     yahoo.com         754333
       3016711          50.000         W  12570  462.0  191.0     yahoo.com         754377
       3016715          50.000         W   9992  455.0  123.0     gmail.com         754441
       3016727          59.000         W  10854  593.0  485.0     yahoo.com         754575
       3016735          59.000         W   9992  455.0  123.0     gmail.com         754656
       3016773          98.000         W  14092  111.0  441.0     gmail.com         755098

--- Cluster 38430 (size 264, fraud_rate 0) ---
 TransactionID  TransactionAmt ProductCD  card1  card2  addr1  P_emaildomain  TransactionDT
       3075635          75.000         R  11516  320.0  269.0    hotmail.com        1872529
       3078892          59.000         W  11516  320.0  269.0      gmail.com        1902154
       3079495          29.000         W  18148  516.0  299.0      gmail.com        1909258
       3080397         201.000         W  17466  225.0  264.0      gmail.com        1941824
       3082030         200.000         R  11516  320.0  191.0      yahoo.com        1961076
       3082550         201.000         W  17466  225.0  264.0      gmail.com        1964391
       3084430         335.000         W  12906  516.0  264.0      gmail.com        1977713
       3084619         107.950         W   9197  555.0  498.0      yahoo.com        1979143
       3084698          57.950         W   9197  555.0  498.0      yahoo.com        1979833
       3084714         107.950         W  14631  476.0  191.0      gmail.com        1979978
       3085108          97.000         W   1690  516.0  310.0            NaN        1983158
       3085311         226.000         W   1893  514.0  204.0  bellsouth.net        1984806
       3085349         201.000         W  17466  225.0  264.0            NaN        1984991
       3085964         201.000         W  17466  225.0  264.0      gmail.com        1990372
       3087420          18.190         C  13050  469.0    NaN    hotmail.com        2036173
       3087760         100.000         R   5893  399.0  170.0         me.com        2041242
       3087772         125.000         R  15775  481.0  325.0  earthlink.net        2041402
       3087779         114.035         C  13050  469.0    NaN  anonymous.com        2041448
       3087785         205.470         W   9500  321.0  204.0    outlook.com        2041514
       3087796         100.000         R   6019  583.0  469.0    hotmail.com        2041631
       3087799         226.000         W  15604  314.0  299.0      gmail.com        2041663
       3087801         114.950         W  11516  320.0  327.0        msn.com        2041675
       3087805         100.000         H   1724  583.0  204.0  anonymous.com        2041712
       3087806         161.000         W   7919  194.0  325.0      yahoo.com        2041721
       3087809         100.000         R  16544  399.0  472.0      gmail.com        2041731
       3087836         100.000         R   7166  435.0  476.0  anonymous.com        2042031
       3087839          98.190         W   2538  476.0  110.0            NaN        2042048
       3087840         117.000         W   4806  490.0  315.0        att.net        2042052
       3087952         201.000         W  17466  225.0  264.0      gmail.com        2043308
       3087963         335.000         W   6019  583.0  123.0        aol.com        2043426
       3088145         320.000         W  11233  321.0  184.0      yahoo.com        2045324
       3088159          35.950         W  14631  476.0  498.0      yahoo.com        2045463
       3090426          57.950         W  14631  476.0  191.0      gmail.com        2064186
       3090451         150.000         R   6414  216.0  299.0      gmail.com        2064391
       3091027           6.180         C   5365  177.0    NaN    hotmail.com        2069430
       3091032         335.000         W  12906  516.0  264.0      gmail.com        2069485
       3091040           6.180         C   5365  177.0    NaN    hotmail.com        2069550
       3091045           6.180         C   5365  177.0    NaN    hotmail.com        2069620
       3091072          23.950         W  14631  476.0  476.0      gmail.com        2069893
       3091200          25.000         H   1974  111.0  184.0      gmail.com        2071062
       3091212          25.000         S  15491  399.0  184.0            NaN        2071136
       3091216          10.436         C   1976  545.0    NaN      gmail.com        2071171
       3091240          14.458         C  14276  177.0    NaN    hotmail.com        2071383
       3091386         200.000         R   5145  555.0  472.0      gmail.com        2072796
       3091425         200.000         R   8966  399.0  123.0  sbcglobal.net        2073074
       3091428          29.000         W   7153  216.0  225.0            NaN        2073096
       3091459         312.610         W   4278  516.0  110.0      gmail.com        2073306
       3091460         280.000         W   1675  174.0  204.0      gmail.com        2073316
       3091465          30.950         W  11233  321.0  330.0            NaN        2073368
       3091563          87.000         W  11233  321.0  126.0            NaN        2074305
       3091764         201.000         W  17466  225.0  264.0            NaN        2076366
       3091786         141.000         W  17466  225.0  264.0            NaN        2076647
       3091811         226.000         W   2538  476.0  387.0      gmail.com        2076821
       3091816         226.000         W  17466  225.0  264.0            NaN        2076866
       3091832         226.000         W   2538  476.0  387.0      gmail.com        2077051
       3092264          31.950         W  11233  321.0  272.0      yahoo.com        2082033
       3092346         108.950         W   2538  476.0  205.0      yahoo.com        2083147
       3092623          83.950         W  14631  476.0  299.0      gmail.com        2087424
       3092692         150.000         R   6288  181.0  123.0      gmail.com        2088967
       3092706          10.611         C  13050  469.0    NaN    hotmail.com        2089310
       3092920          50.000         H  10112  360.0  327.0      gmail.com        2094402
       3092923          50.000         R  16659  170.0  325.0  earthlink.net        2094537
       3092925          60.000         H  15491  399.0  325.0        aol.com        2094580
       3092939          50.000         H  11319  155.0  123.0  sbcglobal.net        2095053
       3092940          50.000         H   6288  181.0  203.0      yahoo.com        2095074
       3093087           6.180         C   5365  177.0    NaN    hotmail.com        2107101
       3093106         226.000         W  17466  225.0  264.0      gmail.com        2110379
       3093112         226.000         W  17466  225.0  264.0      gmail.com        2111102
       3093318         150.000         R   9781  399.0  441.0      yahoo.com        2123087
       3093838         150.000         R  13143  170.0  299.0  anonymous.com        2130340
       3093865         150.000         R  11319  155.0  226.0      gmail.com        2130689
       3093876         200.000         R   4726  555.0  272.0  anonymous.com        2130794
       3093952         100.000         R  16659  170.0  231.0      gmail.com        2131499
       3093958          50.000         R   2616  327.0  204.0      gmail.com        2131525
       3093977          50.000         H   6019  583.0  226.0        twc.com        2131689
       3093999          93.598         C  13050  469.0    NaN      gmail.com        2131858
       3094008          30.000         H  11319  155.0  272.0      gmail.com        2131887
       3094565          58.430         W   4278  516.0  110.0      yahoo.com        2136670
       3094735          15.000         S  11919  170.0  330.0            NaN        2137987
       3095611          15.000         H  15847  216.0  444.0    hotmail.com        2144753
       3095777          59.000         W  11919  170.0  264.0      yahoo.com        2145838
       3095949        1331.000         W  11233  321.0  126.0      yahoo.com        2147138
       3095955         995.000         W  11233  321.0  126.0      yahoo.com        2147194
       3095999          25.000         H  14037  111.0  204.0      gmail.com        2147440
       3096001          40.000         H   9781  399.0  337.0      gmail.com        2147461
       3096002          50.000         H  11196  399.0  299.0      yahoo.com        2147474
       3096003          25.000         H   9350  111.0  512.0       live.com        2147477
       3096014          50.000         H  17188  321.0  220.0    hotmail.com        2147562
       3096015          50.000         R  16659  170.0  204.0      gmail.com        2147564
       3096031          59.000         W   9175  111.0  126.0      gmail.com        2147687
       3096034          50.000         H  14631  476.0  231.0      gmail.com        2147716
       3096039          25.000         H   9500  321.0  204.0      yahoo.com        2147752
       3096044          75.000         H  12817  516.0  512.0    comcast.net        2147800
       3096053          50.000         H  15066  170.0  325.0        aol.com        2147867
       3096054          30.000         H  15063  514.0  299.0      yahoo.com        2147872
       3096062          25.000         H  15847  216.0  485.0        cox.net        2147934
       3096072          30.000         H  15497  490.0  299.0    hotmail.com        2148008
       3096081          50.000         R  11233  321.0  272.0    comcast.net        2148110
       3096084          50.000         R   2884  490.0  420.0  anonymous.com        2148121
       3096086          55.000         H   2616  327.0  441.0      gmail.com        2148129
       3096089          50.000         R  11233  321.0  272.0    comcast.net        2148150
       3096090          25.000         S  12501  490.0  181.0            NaN        2148167
       3096092          50.000         H   5002  555.0  512.0  anonymous.com        2148193
       3096097          40.000         H   2803  100.0  441.0      yahoo.com        2148223
       3096106          50.000         R   7664  490.0  264.0      yahoo.com        2148285
       3096785          50.000         H   3998  399.0  337.0      yahoo.com        2153477
       3096844         117.766         C   5365  177.0    NaN    hotmail.com        2154043
       3096913          75.000         R  10486  514.0  264.0      gmail.com        2154676
       3096940          50.000         R  11919  170.0  204.0      gmail.com        2154949
       3096974         100.000         R   2616  327.0  441.0      gmail.com        2155146
       3096978         100.000         R   2616  327.0  441.0      gmail.com        2155210
       3097346          55.036         C   5365  177.0    NaN    hotmail.com        2158108
       3097378          50.000         H   6481  111.0  337.0    comcast.net        2158350
       3097381          54.500         W   3605  514.0  325.0      gmail.com        2158380
       3097391          50.000         R  11862  562.0  184.0      gmail.com        2158502
       3097395          60.000         H  17400  174.0  123.0      gmail.com        2158526
       3097398          58.950         W  11919  170.0  330.0            NaN        2158538
       3097403          68.500         W  11919  170.0  325.0  anonymous.com        2158596
       3097415          48.950         W  11919  170.0  330.0            NaN        2158713
       3097422          50.000         H  10057  225.0  204.0        aol.com        2158777
       3097429          59.000         W   2392  360.0  272.0      ymail.com        2158863
       3097434          50.000         H  12221  543.0  170.0      gmail.com        2158896
       3097438          59.000         W  17635  565.0  325.0      yahoo.com        2158950
       3097442          57.240         C  15885  545.0    NaN      gmail.com        2158956
       3097444          50.000         R   7005  111.0  310.0      gmail.com        2158980
       3097454          50.000         R  11319  155.0  231.0    comcast.net        2159074
       3097638          50.000         H   3605  514.0  126.0      gmail.com        2160806
       3097776          15.950         W  11919  170.0  264.0      yahoo.com        2162150
       3097848          25.000         S  17917  555.0  203.0            NaN        2163052
       3097880          25.000         H   9891  583.0  299.0        cox.net        2163395
       3097895          25.000         H   4726  555.0  204.0      gmail.com        2163484
       3097907          50.000         H  11319  155.0  512.0      gmail.com        2163594
       3097918         102.000         W   9500  321.0  204.0      gmail.com        2163675
       3097920         150.000         R   9571  399.0  299.0    hotmail.com        2163683
       3097927         117.000         W   2755  404.0  308.0      gmail.com        2163762
       3097942         100.000         R   9803  583.0  191.0      gmail.com        2163916
       3097944         100.000         R  16972  174.0  204.0      gmail.com        2163944
       3097948         117.000         W   7585  553.0  181.0      yahoo.com        2163987
       3097952         100.000         R  11319  155.0  384.0      gmail.com        2164027
       3097957         100.000         R  11890  399.0  299.0      gmail.com        2164052
       3097958         100.000         R   6019  583.0  315.0      yahoo.com        2164059
       3097961         200.000         R  10893  399.0  181.0      gmail.com        2164135
       3097965         100.000         R   9781  399.0  387.0      gmail.com        2164163
       3097977         114.950         W   4272  111.0  299.0            NaN        2164332
       3097980         117.000         W  16435  298.0  337.0      yahoo.com        2164400
       3097981         100.000         R   7826  481.0  387.0  anonymous.com        2164427
       3097987         100.000         R   2803  100.0  264.0      ymail.com        2164468
       3097988         125.000         R   3682  264.0  184.0      gmail.com        2164473
       3097989         125.000         R   4806  490.0  299.0      gmail.com        2164475
       3097992         107.950         W   1333  170.0  315.0      gmail.com        2164497
       3098284          47.950         W   3605  514.0  325.0      gmail.com        2168176
       3098476         150.000         H  11319  155.0  123.0  anonymous.com        2170343
       3098484         100.000         R   8695  170.0  433.0      yahoo.com        2170469
       3098500         100.000         R   6019  583.0  299.0      gmail.com        2170707
       3098535         125.000         R  11319  155.0  472.0      gmail.com        2171010
       3098643          49.000         W   9885  481.0  264.0      gmail.com        2172480
       3098981         250.000         R   6288  181.0  177.0      gmail.com        2176997
       3098989         125.000         R  11919  170.0  315.0      gmail.com        2177104
       3098997         150.000         R  16659  170.0  325.0      yahoo.com        2177182
       3099130         100.000         R   7815  161.0  123.0      ymail.com        2179037
       3099140         100.000         R  11319  155.0  315.0    comcast.net        2179215
       3099264          23.786         C   5365  177.0    NaN      gmail.com        2181647
       3099272          25.000         H   8406  264.0  299.0      gmail.com        2181779
       3099279          25.000         H   6554  592.0  272.0      gmail.com        2181936
       3099297          27.284         C   5365  177.0    NaN      gmail.com        2182443
       3099298          27.284         C   5365  177.0    NaN      gmail.com        2182494
       3099632          50.000         H  11319  155.0  325.0      yahoo.com        2197166
       3099674          50.000         R  11319  155.0  184.0    hotmail.com        2201630
       3099706          30.950         W  17635  565.0  123.0      gmail.com        2204347
       3099835         150.000         H  11919  170.0  126.0      gmail.com        2207710
       3099885         108.500         W  16659  170.0  441.0      yahoo.com        2208607
       3099896         100.000         R   3682  264.0  184.0  anonymous.com        2208818
       3099904         100.000         R  11106  100.0  337.0      gmail.com        2208891
       3099908         100.000         R  10447  490.0  315.0    hotmail.com        2208952
       3099910         100.000         R  16659  170.0  204.0      gmail.com        2208972
       3099915         117.000         W   9885  481.0  264.0      yahoo.com        2209103
       3099924         100.000         R  16075  514.0  330.0      gmail.com        2209209
       3099925         100.000         R  11919  170.0  472.0        aol.com        2209247
       3099927         125.000         R  11890  399.0  204.0      yahoo.com        2209331
       3100135         117.000         W  17635  565.0  325.0      gmail.com        2211753
       3100159         250.000         R  11319  155.0  126.0      gmail.com        2211966
       3100186         150.000         H   8972  399.0  272.0      yahoo.com        2212321
       3100199         150.000         H   6554  592.0  272.0      yahoo.com        2212466
       3100211         200.000         R  11890  399.0  204.0  anonymous.com        2212672
       3100220         200.000         R  11890  399.0  204.0  anonymous.com        2212794
       3100224         150.000         H   6554  592.0  272.0      yahoo.com        2212830
       3100229         125.000         R  16009  170.0  181.0      gmail.com        2212855
       3100702         200.000         R  17400  174.0  181.0      gmail.com        2217604
       3100711          71.534         C   5365  177.0    NaN    hotmail.com        2217696
       3100714         250.000         R   6019  583.0  325.0        msn.com        2217743
       3100725          71.534         C   5365  177.0    NaN    hotmail.com        2217840
       3100747         311.950         W  16659  170.0  231.0            NaN        2218098
       3100772         150.000         H  10616  583.0  205.0        cox.net        2218342
       3100785         200.000         R  11319  155.0  315.0      gmail.com        2218406
       3100808          71.534         C   5365  177.0    NaN    hotmail.com        2218586
       3100930          85.818         C   5365  177.0    NaN    hotmail.com        2219650
       3100963         107.950         W   3605  514.0  325.0        aol.com        2220024
       3101006          89.549         C   5365  177.0    NaN    hotmail.com        2220452
       3101010         100.000         R   9350  111.0  512.0  anonymous.com        2220463
       3101020         100.000         R  10616  583.0  315.0    hotmail.com        2220619
       3101035         100.000         H  16132  111.0  299.0        cox.net        2220753
       3101051         100.000         R  11839  490.0  123.0  anonymous.com        2220941
       3101052         100.000         H   6019  583.0  299.0      yahoo.com        2220965
       3101063         100.000         H   6070  315.0  428.0      gmail.com        2221030
       3101076         100.000         R   3998  399.0  512.0      gmail.com        2221152
       3101078         100.000         R  18132  567.0  204.0        msn.com        2221179
       3101206          47.950         W   8556  433.0  251.0      gmail.com        2222269
       3101210          49.000         W  11233  321.0  272.0      gmail.com        2222330
       3101280          49.000         W  11157  215.0  204.0      gmail.com        2222933
       3101857         103.970         W  11919  170.0  325.0      yahoo.com        2228160
       3101951         100.000         R  11319  155.0  225.0    comcast.net        2229162
       3102345          25.000         H  11919  170.0  387.0      gmail.com        2233402
       3102349          25.000         H  11919  170.0  387.0      gmail.com        2233451
       3102437          21.000         W   6554  592.0  272.0      gmail.com        2234670
       3103693          75.000         R  11319  155.0  472.0      yahoo.com        2254566

 TransactionID  TransactionAmt ProductCD  card1  card2  addr1  P_emaildomain  TransactionDT
       3080057         107.950         W   5700  122.0  264.0      gmail.com        1918778
       3083234          57.950         W   5700  122.0  272.0      gmail.com        1968964
       3085100          59.000         W   1047  560.0  492.0    hotmail.com        1983123
       3085741         170.950         W   7720  514.0  299.0      yahoo.com        1988331
       3085905         226.000         W   5700  122.0  512.0      gmail.com        1989837
       3086801          57.950         W   5700  122.0  204.0      gmail.com        2002060
       3086976          30.782         C  15885  545.0    NaN    outlook.com        2005443
       3086977          39.000         W   5700  122.0  191.0      gmail.com        2005494
       3086979          34.630         C   9633  296.0    NaN      gmail.com        2005560
       3087302         335.000         W  14059  492.0  410.0      yahoo.com        2031492
       3087455         400.000         R  18234  481.0  472.0  anonymous.com        2036892
       3087483         411.950         W   6892  560.0  330.0      yahoo.com        2037396
       3087628         171.000         W   5700  122.0  512.0      gmail.com        2039439
       3087636         159.950         W   9112  250.0  441.0      yahoo.com        2039679
       3087664         151.474         C  13232  555.0    NaN      gmail.com        2040100
       3088094         100.000         R   1556  314.0  299.0        aol.com        2044778
       3088329         825.000         R   7720  514.0  299.0      gmail.com        2046983
       3088335         825.000         R   7720  514.0  299.0      gmail.com        2047033
       3088368         600.000         R  16659  170.0  325.0  anonymous.com        2047309
       3088371         500.000         R   6892  560.0  387.0        aol.com        2047340
       3088723          18.656         C  13232  555.0    NaN      gmail.com        2050319
       3089152         100.000         R   6019  583.0  315.0      gmail.com        2053807
       3089153         100.000         R  18268  583.0  441.0  anonymous.com        2053811
       3089177         103.970         W  15497  490.0  299.0  anonymous.com        2053930
       3089189         100.000         R  12133  111.0  264.0      gmail.com        2054013
       3089200         100.000         R   5409  170.0  299.0  anonymous.com        2054105
       3089224         100.000         H   3457  555.0  337.0        msn.com        2054302
       3089235         100.000         R  17373  490.0  310.0      yahoo.com        2054362
       3089238         100.000         R  17055  393.0  126.0      gmail.com        2054382
       3089242         100.000         R   9830  555.0  269.0      yahoo.com        2054395
       3089250         100.000         R  10894  399.0  472.0    verizon.net        2054452
       3089256         100.000         H   6892  560.0  204.0        aol.com        2054501
       3089265          90.598         C   6604  555.0    NaN      gmail.com        2054653
       3089312          75.000         W   5700  122.0  204.0            NaN        2055033
       3089610         107.950         W   5700  122.0  253.0      gmail.com        2057358
       3089954         335.000         W   1556  314.0  299.0      gmail.com        2060241
       3089955         335.000         W  11453  225.0  251.0    comcast.net        2060243
       3089966         100.000         R  15471  555.0  299.0     icloud.com        2060314
       3089969         100.000         H   9500  321.0  204.0      gmail.com        2060332
       3089980         150.000         R   7720  514.0  299.0     icloud.com        2060415
       3089989         150.000         R   7720  514.0  299.0     icloud.com        2060490
       3089990         300.000         R   5658  399.0  299.0  sbcglobal.net        2060506
       3089994         500.000         R   6019  583.0  264.0      yahoo.com        2060559
       3090005         150.000         R   7720  514.0  299.0     icloud.com        2060655
       3090024         250.000         R  11919  170.0  441.0      gmail.com        2060833
       3090029         150.000         R  18268  583.0  469.0      gmail.com        2060880
       3090032         319.950         W  14426  111.0  272.0      gmail.com        2060938
       3090039         100.000         S   6771  399.0  204.0            NaN        2061011
       3091093          39.360         W   1431  492.0  343.0            NaN        2070092
       3091095          30.000         H  10894  399.0  325.0      gmail.com        2070101
       3091104          25.000         H  15316  252.0  184.0      gmail.com        2070188
       3091187          29.410         W  10317  492.0  343.0  anonymous.com        2070938
       3091463          50.000         H   6892  560.0  330.0  anonymous.com        2073329
       3091651          56.500         W   5700  122.0  441.0      ymail.com        2075213
       3092816          67.950         W   1556  314.0  299.0            NaN        2091851
       3092972          19.500         W   5606  318.0  204.0      gmail.com        2096373
       3092985          25.000         H   1556  314.0  299.0      yahoo.com        2096920
       3093425         100.000         R  16661  490.0  327.0      gmail.com        2125014
       3093426         107.990         W   1556  314.0  299.0      gmail.com        2125081
       3093432         100.000         R   5167  361.0  126.0      gmail.com        2125186
       3093443         100.000         R  17400  174.0  181.0  anonymous.com        2125411
       3093445         100.000         R   9500  321.0  325.0      gmail.com        2125423
       3093449         100.000         R  13220  562.0  123.0      yahoo.com        2125516
       3094033         370.000         W   5700  122.0  387.0      yahoo.com        2132176
       3094212         100.000         R   6892  560.0  315.0        aol.com        2133639
       3094438         200.000         R   6771  399.0  231.0  optonline.net        2135703
       3094442         100.000         R   9803  583.0  325.0      gmail.com        2135723
       3094493         100.000         H  13526  529.0  177.0      gmail.com        2136103
       3094500          50.000         R  16141  399.0  337.0    verizon.net        2136151
       3094531         100.000         R   7676  512.0  299.0      gmail.com        2136373
       3094533          75.000         R   9749  181.0  231.0      gmail.com        2136380
       3094555         100.000         R   6474  514.0  299.0      gmail.com        2136581
       3094784          50.000         H  10894  399.0  299.0      gmail.com        2138432
       3094804         100.000         R   4763  111.0  231.0      gmail.com        2138589
       3094821         100.000         R  18227  583.0  126.0      gmail.com        2138735
       3094826         150.000         R  10486  514.0  315.0      yahoo.com        2138753
       3094850         125.000         R   2616  327.0  469.0      gmail.com        2138891
       3094859          40.000         H   6203  555.0  225.0      gmail.com        2138946
       3094871          75.000         R   6019  583.0  299.0      gmail.com        2139056
       3094898          50.000         H   6019  583.0  272.0    hotmail.com        2139207
       3095370         150.000         R  17868  148.0  472.0    hotmail.com        2142961
       3095372         175.000         R   9803  583.0  110.0        msn.com        2142967
       3095377          75.000         R   9500  321.0  264.0      gmail.com        2142977
       3095381         200.000         R  12100  554.0  231.0      yahoo.com        2143008
       3095384         117.000         W   2581  199.0  325.0      yahoo.com        2143032
       3095388         150.000         R  10616  583.0  315.0      yahoo.com        2143054
       3095390         200.000         R   1556  314.0  299.0      gmail.com        2143086
       3095392         100.000         R   9370  321.0  272.0        aol.com        2143090
       3095396         250.000         R  17188  321.0    NaN      yahoo.com        2143115
       3095400         100.000         S  15063  514.0  476.0            NaN        2143145
       3095404         100.000         R   7005  111.0  299.0  anonymous.com        2143158
       3095412         131.016         C  16136  204.0    NaN      gmail.com        2143246
       3095414         100.000         R  11839  490.0  269.0      gmail.com        2143268
       3095416         200.000         R   6771  399.0  310.0      gmail.com        2143284
       3095417         281.350         W   5700  122.0  343.0            NaN        2143294
       3095429         117.000         W  14128  170.0  191.0      gmail.com        2143392
       3095430         125.000         H   6174  490.0  387.0  bellsouth.net        2143403
       3095434         200.000         R   2455  321.0  299.0    comcast.net        2143422
       3095437         100.000         R   9803  583.0  337.0      gmail.com        2143452
       3095449         100.000         R  10894  399.0  299.0      gmail.com        2143604
       3095451          75.000         R   4679  555.0  126.0      gmail.com        2143619
       3095464         118.020         W   1431  492.0  343.0            NaN        2143716
       3095465          75.000         H   8987  436.0  441.0        aol.com        2143717
       3095474         175.000         R   6019  583.0  330.0      gmail.com        2143804
       3095476          75.000         H   8987  436.0  441.0        aol.com        2143806
       3095478         100.000         R   9409  399.0  387.0  anonymous.com        2143806
       3095486         300.000         H  12932  361.0  325.0      ymail.com        2143848
       3095487         150.000         R  16132  111.0  299.0      gmail.com        2143850
       3095489         100.000         R   9409  399.0  387.0  anonymous.com        2143862
       3095491          75.000         R  11207  361.0  231.0    comcast.net        2143864
       3095494          72.992         C   1085  500.0    NaN      gmail.com        2143890
       3095499         325.550         W  11585  555.0  299.0      gmail.com        2143932
       3095500         125.000         R  14695  396.0  315.0      yahoo.com        2143934
       3095512         150.000         R   1724  583.0  126.0      gmail.com        2144031
       3095514         150.000         R  10616  583.0  184.0      gmail.com        2144035
       3095516          72.992         C   4329  238.0    NaN      gmail.com        2144053
       3095525         200.000         R   8937  399.0  204.0      gmail.com        2144099
       3095527         125.000         R  16659  170.0  476.0        aol.com        2144103
       3095535         200.000         R  11207  361.0  325.0      yahoo.com        2144173
       3095539         335.000         W   9390  555.0  226.0      yahoo.com        2144244
       3095546         200.000         R   6741  583.0  264.0  anonymous.com        2144296
       3095548          75.000         R   3682  264.0  472.0      gmail.com        2144340
       3095559         100.000         R   6019  583.0  299.0        att.net        2144431
       3095561         400.000         R  10616  583.0  264.0    hotmail.com        2144453
       3095566         100.000         R  15757  322.0  299.0      gmail.com        2144470
       3095571         171.000         W  17926  124.0  269.0 windstream.net        2144488
       3095572         300.000         R  16132  111.0  299.0        aol.com        2144491
       3095582          77.000         W   2884  490.0  325.0      yahoo.com        2144562
       3095587          75.000         R  10894  399.0  204.0    hotmail.com        2144602
       3095590         150.000         H   9500  321.0  325.0    hotmail.com        2144617
       3095593         150.000         H  18366  111.0  220.0      ymail.com        2144641
       3095595          75.000         H   8695  170.0  264.0      yahoo.com        2144652
       3095597          75.000         R  10894  399.0  204.0    hotmail.com        2144656
       3095602         150.000         R   6054  327.0  191.0      gmail.com        2144689
       3095757          15.000         H   3760  555.0  264.0      gmail.com        2145737
       3095808          25.000         H   8946  556.0  225.0  anonymous.com        2146048
       3095821         159.950         W   1556  314.0  299.0    hotmail.com        2146127
       3095833          13.992         C   5583  103.0    NaN    hotmail.com        2146197
       3095836          25.000         H   8987  436.0  441.0      gmail.com        2146211
       3095848          25.000         H   8014  399.0  420.0  anonymous.com        2146256
       3095877          15.000         H  15063  514.0  299.0      gmail.com        2146492
       3096005          20.000         W   5700  122.0  181.0      gmail.com        2147504
       3096407          36.950         W   5700  122.0  204.0            NaN        2150588
       3096627          57.950         W   1359  314.0  299.0      yahoo.com        2152225
       3096709         201.000         W   5700  122.0  387.0      yahoo.com        2152765
       3096763         188.000         W   5700  122.0  387.0            NaN        2153292
       3096849         900.000         R   7164  399.0  441.0  anonymous.com        2154080
       3096909          57.950         W   3094  276.0  191.0      yahoo.com        2154642
       3096916          50.000         H   9002  453.0  337.0      gmail.com        2154693
       3096917          47.950         W  16972  174.0  269.0      gmail.com        2154696
       3096918          34.105         C   9633  296.0    NaN      gmail.com        2154724
       3096922          67.950         W   8868  205.0  485.0      gmail.com        2154749
       3096924          39.000         W   8868  205.0  204.0      gmail.com        2154766
       3096928          30.316         C  15885  545.0    NaN    hotmail.com        2154806
       3096935          39.000         W   1556  314.0  299.0      gmail.com        2154907
       3096944          38.690         C  15885  545.0    NaN    hotmail.com        2154963
       3096945          50.000         R  16659  170.0  472.0      yahoo.com        2154967
       3096946          50.000         R   1431  492.0  343.0        msn.com        2154978
       3096948          50.000         H   7861  494.0  299.0      gmail.com        2154995
       3096951          29.500         W   8148  206.0  325.0      yahoo.com        2155007
       3096953          39.000         W  17245  555.0  299.0      gmail.com        2155016
       3096956          50.000         H  13849  399.0  184.0      gmail.com        2155025
       3096964          50.000         H  12501  490.0  181.0      gmail.com        2155082
       3096982          50.000         R   8406  264.0  205.0      gmail.com        2155268
       3096984          39.000         W  14290  512.0  315.0  sbcglobal.net        2155273
       3096997          50.000         H  16075  514.0  184.0      gmail.com        2155391
       3097440        1321.950         W   9390  555.0  122.0      gmail.com        2158955
       3097463         150.000         R   1431  492.0  343.0      gmail.com        2159146
       3097583          53.970         W   9316    NaN  469.0      gmail.com        2160267
       3098238          29.000         W   5700  122.0  325.0      gmail.com        2167644
       3098464          39.000         W   5606  318.0  191.0      gmail.com        2170225
       3098521          87.950         W   2581  199.0  315.0      gmail.com        2170878
       3099073         150.000         R  13526  529.0  264.0  anonymous.com        2178275
       3099614          50.000         R   6771  399.0  441.0  anonymous.com        2195083
       3100000          75.000         H   9500  321.0  126.0      gmail.com        2210423
       3100058         100.000         R   5329  555.0  204.0      gmail.com        2211021
       3100070         100.000         H   3682  264.0  264.0      gmail.com        2211105
       3101306         250.000         R  10486  514.0  512.0        msn.com        2223099
       3101395         300.000         R   6019  583.0  299.0      gmail.com        2223716
       3101401         300.000         R   9370  321.0  204.0    comcast.net        2223779
       3101877         100.000         R  16075  514.0  315.0    comcast.net        2228406
       3101881         125.000         R   6054  327.0  433.0      gmail.com        2228442
       3101885         100.000         R  14998  562.0  472.0      yahoo.com        2228458
       3101893          99.343         C  15885  545.0    NaN    hotmail.com        2228510
       3101894          75.000         R  11207  361.0  384.0    comcast.net        2228514
       3101896         125.000         R  17644  390.0  299.0      gmail.com        2228522
       3101898         150.000         R  15359  562.0  384.0      gmail.com        2228559
       3101900          68.950         W  17188  321.0  299.0      gmail.com        2228588
       3101905         100.000         R  16742  543.0  251.0      gmail.com        2228633
       3101908         200.000         R  16326  321.0  126.0      gmail.com        2228682
       3101909         100.000         R  18268  583.0  299.0      gmail.com        2228694
       3101911         108.950         W  11690  111.0  327.0      yahoo.com        2228740
       3101914         100.000         R   6019  583.0  299.0      yahoo.com        2228799
       3101922         200.000         R  13374  111.0  205.0      gmail.com        2228862
       3101924         150.000         H   1873  555.0  296.0      gmail.com        2228866
       3101927         100.000         R   6771  399.0  126.0      yahoo.com        2228895
       3101930         125.000         R   6054  327.0  433.0      gmail.com        2228909
       3101931         150.000         H   1873  555.0  296.0      gmail.com        2228920
       3101932         125.000         R   6054  327.0  433.0      gmail.com        2228934
       3101935         100.000         H   2884  490.0  387.0      yahoo.com        2228990
       3101938         150.000         H   1873  555.0  296.0      gmail.com        2229007
       3101944         100.000         R  12544  321.0  337.0      yahoo.com        2229082
       3101946         125.000         R   5033  269.0  264.0      gmail.com        2229114
       3101947         100.000         R   6019  583.0  205.0        cox.net        2229127
       3101950         100.000         R   9502  553.0  299.0        aol.com        2229159
       3101953         125.000         R   6054  327.0  433.0      gmail.com        2229183
       3101959         125.000         R   6054  327.0  433.0      gmail.com        2229232
       3101960         150.000         R   7164  399.0  299.0  anonymous.com        2229259
       3102103          50.000         H   2884  490.0  181.0      gmail.com        2230455
       3102119          50.000         R   1359  314.0  299.0    verizon.net        2230615
       3102155         100.000         R   9180  543.0  441.0      gmail.com        2231137
       3102159         100.000         H   9502  553.0  512.0      gmail.com        2231166
       3102169         100.000         H   2803  100.0  184.0        aol.com        2231294
       3102173         208.000         W  15063    NaN  143.0  sbcglobal.net        2231313
       3102174          97.000         W  14861  302.0  436.0      yahoo.com        2231322
       3102176         150.000         R   5329  555.0  299.0  sbcglobal.net        2231358

## Save ring evaluation results

In [8]:
ring_results = {
    'population_fraud_rate': population_fraud_rate,
    'total_fraud': total_fraud,
    'headline_min_size_2': result_min2,
    'sensitivity_by_min_size': sensitivity.reset_index().to_dict(orient='records'),
    'edge_type_breakdown': summary.reset_index().to_dict(orient='records'),
    'behavioral_only_cluster_count': int(behavioral_only_count),
    'false_positive_cluster_count': int(len(false_positive_clusters)),
}

with open('../results/ring_evaluation_metrics.json', 'w') as f:
    json.dump(ring_results, f, indent=2, default=str)

print('Saved to results/ring_evaluation_metrics.json')

Saved to results/ring_evaluation_metrics.json

## Takeaway

_Fill in after running: the fraud lift and capture rate at the headline threshold, whether the finding holds across all three sensitivity thresholds, whether behavioral-only clusters actually concentrate fraud (the number that justifies signal 3), and one honest note on what the false-positive audit revealed._